In [67]:
import pandas as pd
import numpy as np

In [68]:
cd /Users/yanglingxi/Desktop

/Users/yanglingxi/Desktop

In [69]:
df = pd.read_csv('combined_usaid_Nov_18.csv')
df

,uuid,region,country,proj_nm,st_date,end_date,awd_amount,awd_value,implementer,sector,...,desc_sub_score,res_senti_score,res_sub_score,Topic0,Topic1,Topic2,Topic3,Topic4,dominant_topic,cosine_sim_cluster
0,1,South and Central Asia (SCA),Afghanistan,Assistance for Afghanistan's Anti-Corruption A...,2010,2013,e) $25 M-$50 M,26642989,Management Systems International (MSI),Independent Agencies,...,0.574667,0.120000,0.713333,0.03,0.03,0.03,0.03,0.89,4,82
1,2,South and Central Asia (SCA),Afghanistan,Rule of Law Stabilization Program - Formal Com...,2010,2012,e) $25 M-$50 M,33700000,TetraTech ARD,Rule of Law,...,0.466667,-0.033333,0.500000,0.03,0.03,0.03,0.41,0.49,4,11
2,3,South and Central Asia (SCA),Afghanistan,Afghanistan Rule of Law Stabilization Project ...,2011,2012,c) $5 M-$10 M,10000000,"Checchi and Company Consulting, Inc.",Rule of Law,...,0.400000,-0.050000,0.400000,0.05,0.05,0.05,0.81,0.05,3,12
3,4,South and Central Asia (SCA),Afghanistan,Political Party Assessment,2012,2012,a) <$1 M,NaN,"Checchi and Company Consulting, Inc.",Elections and Political Processes,...,0.380000,0.172727,0.713636,0.04,0.04,0.12,0.04,0.74,4,49
4,30,Europe and Eurasia (E&E),Albania,Justice Sector Strengthening Project (JuST),2010,2015,c) $5 M-$10 M,9012613,Chemonics,Rule of Law,...,0.341667,-0.040000,0.473333,0.04,0.04,0.04,0.46,0.43,3,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,311,Middle East and North Africa (MENA),Yemen,Responsive Governance Project (RGP),2010,2015,e) $25 M-$50 M,43000000,Counterpart International,Civil Society,...,0.513333,-0.023333,0.706667,0.03,0.03,0.03,0.03,0.90,4,41
311,312,Middle East and North Africa (MENA),Yemen,Enhancing Government Effectiveness Project (EGE),2007,2010,b) $1 M-$5 M,2939048,Management Systems International (MSI),Governance,...,0.000000,-0.062500,0.187500,0.04,0.04,0.04,0.04,0.85,4,80
312,313,Middle East and North Africa (MENA),Yemen,Basic Health Services Project (BHS),2006,2010,d) $10 M-$25 M,21610314.78,Pathfinder International,Healthcare,...,0.125000,0.165714,0.391429,0.04,0.04,0.22,0.04,0.65,4,83
313,314,Sub-Saharan Africa (SSA),Zambia,Zambia Threshold Project (ZTP),2006,2008,d) $10 M-$25 M,22735000,Chemonics,Rule of Law,...,1.000000,-0.171429,0.642857,0.04,0.04,0.04,0.83,0.04,3,66
314,315,Sub-Saharan Africa (SSA),Zambia,Zambia Institutional Reform Program,2010,2013,b) $1 M-$5 M,4807018,TetraTech ARD,Governance,...,0.452778,-0.500000,1.000000,0.03,0.03,0.03,0.03,0.86,4,89

In [70]:
df_1=pd.read_csv('country_df.csv')
df_1

,country,duration_mean,duration_min,duration_max,duration_median,topic0_mean,topic0_min,topic0_max,topic0_median,topic1_mean,...,topic2_max,topic2_median,topic3_mean,topic3_min,topic3_max,topic3_median,topic4_mean,topic4_min,topic4_max,topic4_median
0,Afghanistan,3.071429,0,7,3.0,0.036429,0.03,0.06,0.030,0.037857,...,0.75,0.035,0.176429,0.03,0.84,0.040,0.679643,0.04,0.89,0.835
1,Albania,3.750000,2,5,3.5,0.037500,0.03,0.05,0.040,0.078750,...,0.17,0.040,0.308750,0.03,0.78,0.210,0.523750,0.04,0.87,0.565
2,Angola,5.000000,5,5,5.0,0.030000,0.03,0.03,0.030,0.030000,...,0.03,0.030,0.030000,0.03,0.03,0.030,0.870000,0.87,0.87,0.870
3,Armenia,4.250000,4,5,4.0,0.035000,0.03,0.04,0.035,0.035000,...,0.04,0.035,0.035000,0.03,0.04,0.035,0.862500,0.83,0.89,0.865
4,Azerbaijan,2.800000,1,4,3.0,0.032000,0.03,0.04,0.030,0.032000,...,0.04,0.030,0.150000,0.03,0.62,0.030,0.752000,0.30,0.87,0.870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Ukraine,3.375000,2,5,3.0,0.035000,0.03,0.04,0.035,0.041250,...,0.07,0.035,0.541250,0.03,0.83,0.660,0.338750,0.04,0.88,0.215
70,Vietnam,3.500000,3,4,3.5,0.040000,0.04,0.04,0.040,0.040000,...,0.04,0.040,0.845000,0.84,0.85,0.845,0.040000,0.04,0.04,0.040
71,West Bank and Gaza,4.200000,2,6,4.5,0.034000,0.03,0.05,0.030,0.034000,...,0.16,0.030,0.313000,0.03,0.88,0.040,0.580000,0.03,0.90,0.785
72,Yemen,4.000000,3,5,4.0,0.036667,0.03,0.04,0.040,0.036667,...,0.22,0.040,0.036667,0.03,0.04,0.040,0.800000,0.65,0.90,0.850
73,Zambia,2.500000,2,3,2.5,0.035000,0.03,0.04,0.035,0.035000,...,0.04,0.035,0.430000,0.03,0.83,0.430,0.450000,0.04,0.86,0.450

In [71]:
dominant_topic_4_count=df[df['dominant_topic'] == 4 ].groupby('country')['dominant_topic'].count()
dominant_topic_4_count

country
Afghanistan           23
Albania                5
Angola                 1
Armenia                4
Azerbaijan             4
                      ..
Uganda                 2
Ukraine                2
West Bank and Gaza     7
Yemen                  3
Zambia                 1
Name: dominant_topic, Length: 68, dtype: int64

In [72]:
dominant_topic_3_count=df[df['dominant_topic'] == 3 ].groupby('country')['dominant_topic'].mean()
dominant_topic_3_count

country
Afghanistan                           3
Albania                               3
Azerbaijan                            3
Bosnia and Herzegovina                3
Cambodia                              3
Colombia                              3
Democratic Republic of Congo          3
Dominican Republic                    3
Egypt                                 3
Georgia                               3
Guatemala                             3
Honduras                              3
Indonesia                             3
Iraq                                  3
Jordan                                3
Kazakhstan                            3
Kenya                                 3
Kosovo                                3
Kyrgyzstan                            3
Kyrgyzstan, Kazakhstan, Tajikistan    3
Laos                                  3
Lebanon                               3
Libya                                 3
Macedonia                             3
Moldova                               3
Mongolia                              3
Montenegro                            3
Morocco                               3
Nepal                                 3
Nicaragua                             3
Pakistan                              3
Philippines                           3
Russia                                3
Serbia                                3
Ukraine                               3
Vietnam                               3
West Bank and Gaza                    3
Zambia                                3
Name: dominant_topic, dtype: int64

In [73]:
dominant_topic_2_count=df[df['dominant_topic'] == 2 ].groupby('country')['dominant_topic'].mean()
dominant_topic_2_count

country
Afghanistan    2
Guinea         2
Honduras       2
Morocco        2
Name: dominant_topic, dtype: int64

In [74]:
dominant_topic_1_count=df[df['dominant_topic'] == 1 ].groupby('country')['dominant_topic'].mean()
dominant_topic_1_count

country
Paraguay    1
Name: dominant_topic, dtype: int64

In [75]:
dominant_topic_0_count=df[df['dominant_topic'] == 0  ].groupby('country')['dominant_topic'].mean()
dominant_topic_0_count

Series([], Name: dominant_topic, dtype: int64)

In [76]:
import functools

dfs = [df_1,dominant_topic_4_count,dominant_topic_3_count,dominant_topic_2_count,dominant_topic_1_count,dominant_topic_0_count]

df_dominant_topic = functools.reduce(lambda left,right: pd.merge(left,right,on=["country"], how="left"), dfs).fillna(0)
df_dominant_topic

,country,duration_mean,duration_min,duration_max,duration_median,topic0_mean,topic0_min,topic0_max,topic0_median,topic1_mean,...,topic3_median,topic4_mean,topic4_min,topic4_max,topic4_median,dominant_topic_x,dominant_topic_y,dominant_topic_x,dominant_topic_y,dominant_topic
0,Afghanistan,3.071429,0,7,3.0,0.036429,0.03,0.06,0.030,0.037857,...,0.040,0.679643,0.04,0.89,0.835,23.0,3.0,2.0,0.0,0.0
1,Albania,3.750000,2,5,3.5,0.037500,0.03,0.05,0.040,0.078750,...,0.210,0.523750,0.04,0.87,0.565,5.0,3.0,0.0,0.0,0.0
2,Angola,5.000000,5,5,5.0,0.030000,0.03,0.03,0.030,0.030000,...,0.030,0.870000,0.87,0.87,0.870,1.0,0.0,0.0,0.0,0.0
3,Armenia,4.250000,4,5,4.0,0.035000,0.03,0.04,0.035,0.035000,...,0.035,0.862500,0.83,0.89,0.865,4.0,0.0,0.0,0.0,0.0
4,Azerbaijan,2.800000,1,4,3.0,0.032000,0.03,0.04,0.030,0.032000,...,0.030,0.752000,0.30,0.87,0.870,4.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Ukraine,3.375000,2,5,3.0,0.035000,0.03,0.04,0.035,0.041250,...,0.660,0.338750,0.04,0.88,0.215,2.0,3.0,0.0,0.0,0.0
70,Vietnam,3.500000,3,4,3.5,0.040000,0.04,0.04,0.040,0.040000,...,0.845,0.040000,0.04,0.04,0.040,0.0,3.0,0.0,0.0,0.0
71,West Bank and Gaza,4.200000,2,6,4.5,0.034000,0.03,0.05,0.030,0.034000,...,0.040,0.580000,0.03,0.90,0.785,7.0,3.0,0.0,0.0,0.0
72,Yemen,4.000000,3,5,4.0,0.036667,0.03,0.04,0.040,0.036667,...,0.040,0.800000,0.65,0.90,0.850,3.0,0.0,0.0,0.0,0.0
73,Zambia,2.500000,2,3,2.5,0.035000,0.03,0.04,0.035,0.035000,...,0.430,0.450000,0.04,0.86,0.450,1.0,3.0,0.0,0.0,0.0

In [77]:
df_dominant_topic.columns.values[-7]='dominant_topic'

In [78]:
df_dominant_topic.columns.values[-5]
df_dominant_topic.columns.values[-5]='dominant_topic_4_count'

In [79]:
df_dominant_topic.columns.values[-4]
df_dominant_topic.columns.values[-4]='dominant_topic_3_count'

In [80]:
df_dominant_topic.columns.values[-3]
df_dominant_topic.columns.values[-3]='dominant_topic_2_count'

In [81]:
df_dominant_topic.columns.values[-2]
df_dominant_topic.columns.values[-2]='dominant_topic_1_count'

In [82]:
df_dominant_topic.columns.values[-1]
df_dominant_topic.columns.values[-1]='dominant_topic_0_count'

In [83]:
df1=df_dominant_topic[["dominant_topic_4_count","dominant_topic_3_count","dominant_topic_2_count","dominant_topic_1_count","dominant_topic_0_count"]]
df1

,dominant_topic_4_count,dominant_topic_3_count,dominant_topic_2_count,dominant_topic_1_count,dominant_topic_0_count
0,23.0,3.0,2.0,0.0,0.0
1,5.0,3.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0
3,4.0,0.0,0.0,0.0,0.0
4,4.0,3.0,0.0,0.0,0.0
...,...,...,...,...,...
69,2.0,3.0,0.0,0.0,0.0
70,0.0,3.0,0.0,0.0,0.0
71,7.0,3.0,0.0,0.0,0.0
72,3.0,0.0,0.0,0.0,0.0
73,1.0,3.0,0.0,0.0,0.0

In [84]:
df_dominant_topic["max_count_topic_categories"]=df1.eq(df1.max(1), axis=0).dot(df1.columns)

In [85]:
df_dominant_topic

,country,duration_mean,duration_min,duration_max,duration_median,topic0_mean,topic0_min,topic0_max,topic0_median,topic1_mean,...,topic4_mean,topic4_min,dominant_topic,topic4_median,dominant_topic_4_count,dominant_topic_3_count,dominant_topic_2_count,dominant_topic_1_count,dominant_topic_0_count,max_count_topic_categories
0,Afghanistan,3.071429,0,7,3.0,0.036429,0.03,0.06,0.030,0.037857,...,0.679643,0.04,0.89,0.835,23.0,3.0,2.0,0.0,0.0,dominant_topic_4_count
1,Albania,3.750000,2,5,3.5,0.037500,0.03,0.05,0.040,0.078750,...,0.523750,0.04,0.87,0.565,5.0,3.0,0.0,0.0,0.0,dominant_topic_4_count
2,Angola,5.000000,5,5,5.0,0.030000,0.03,0.03,0.030,0.030000,...,0.870000,0.87,0.87,0.870,1.0,0.0,0.0,0.0,0.0,dominant_topic_4_count
3,Armenia,4.250000,4,5,4.0,0.035000,0.03,0.04,0.035,0.035000,...,0.862500,0.83,0.89,0.865,4.0,0.0,0.0,0.0,0.0,dominant_topic_4_count
4,Azerbaijan,2.800000,1,4,3.0,0.032000,0.03,0.04,0.030,0.032000,...,0.752000,0.30,0.87,0.870,4.0,3.0,0.0,0.0,0.0,dominant_topic_4_count
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Ukraine,3.375000,2,5,3.0,0.035000,0.03,0.04,0.035,0.041250,...,0.338750,0.04,0.88,0.215,2.0,3.0,0.0,0.0,0.0,dominant_topic_3_count
70,Vietnam,3.500000,3,4,3.5,0.040000,0.04,0.04,0.040,0.040000,...,0.040000,0.04,0.04,0.040,0.0,3.0,0.0,0.0,0.0,dominant_topic_3_count
71,West Bank and Gaza,4.200000,2,6,4.5,0.034000,0.03,0.05,0.030,0.034000,...,0.580000,0.03,0.90,0.785,7.0,3.0,0.0,0.0,0.0,dominant_topic_4_count
72,Yemen,4.000000,3,5,4.0,0.036667,0.03,0.04,0.040,0.036667,...,0.800000,0.65,0.90,0.850,3.0,0.0,0.0,0.0,0.0,dominant_topic_4_count
73,Zambia,2.500000,2,3,2.5,0.035000,0.03,0.04,0.035,0.035000,...,0.450000,0.04,0.86,0.450,1.0,3.0,0.0,0.0,0.0,dominant_topic_3_count

## sector

In [86]:
df

,uuid,region,country,proj_nm,st_date,end_date,awd_amount,awd_value,implementer,sector,...,desc_sub_score,res_senti_score,res_sub_score,Topic0,Topic1,Topic2,Topic3,Topic4,dominant_topic,cosine_sim_cluster
0,1,South and Central Asia (SCA),Afghanistan,Assistance for Afghanistan's Anti-Corruption A...,2010,2013,e) $25 M-$50 M,26642989,Management Systems International (MSI),Independent Agencies,...,0.574667,0.120000,0.713333,0.03,0.03,0.03,0.03,0.89,4,82
1,2,South and Central Asia (SCA),Afghanistan,Rule of Law Stabilization Program - Formal Com...,2010,2012,e) $25 M-$50 M,33700000,TetraTech ARD,Rule of Law,...,0.466667,-0.033333,0.500000,0.03,0.03,0.03,0.41,0.49,4,11
2,3,South and Central Asia (SCA),Afghanistan,Afghanistan Rule of Law Stabilization Project ...,2011,2012,c) $5 M-$10 M,10000000,"Checchi and Company Consulting, Inc.",Rule of Law,...,0.400000,-0.050000,0.400000,0.05,0.05,0.05,0.81,0.05,3,12
3,4,South and Central Asia (SCA),Afghanistan,Political Party Assessment,2012,2012,a) <$1 M,NaN,"Checchi and Company Consulting, Inc.",Elections and Political Processes,...,0.380000,0.172727,0.713636,0.04,0.04,0.12,0.04,0.74,4,49
4,30,Europe and Eurasia (E&E),Albania,Justice Sector Strengthening Project (JuST),2010,2015,c) $5 M-$10 M,9012613,Chemonics,Rule of Law,...,0.341667,-0.040000,0.473333,0.04,0.04,0.04,0.46,0.43,3,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,311,Middle East and North Africa (MENA),Yemen,Responsive Governance Project (RGP),2010,2015,e) $25 M-$50 M,43000000,Counterpart International,Civil Society,...,0.513333,-0.023333,0.706667,0.03,0.03,0.03,0.03,0.90,4,41
311,312,Middle East and North Africa (MENA),Yemen,Enhancing Government Effectiveness Project (EGE),2007,2010,b) $1 M-$5 M,2939048,Management Systems International (MSI),Governance,...,0.000000,-0.062500,0.187500,0.04,0.04,0.04,0.04,0.85,4,80
312,313,Middle East and North Africa (MENA),Yemen,Basic Health Services Project (BHS),2006,2010,d) $10 M-$25 M,21610314.78,Pathfinder International,Healthcare,...,0.125000,0.165714,0.391429,0.04,0.04,0.22,0.04,0.65,4,83
313,314,Sub-Saharan Africa (SSA),Zambia,Zambia Threshold Project (ZTP),2006,2008,d) $10 M-$25 M,22735000,Chemonics,Rule of Law,...,1.000000,-0.171429,0.642857,0.04,0.04,0.04,0.83,0.04,3,66
314,315,Sub-Saharan Africa (SSA),Zambia,Zambia Institutional Reform Program,2010,2013,b) $1 M-$5 M,4807018,TetraTech ARD,Governance,...,0.452778,-0.500000,1.000000,0.03,0.03,0.03,0.03,0.86,4,89

In [87]:
df['sector'].unique()

array(['Independent Agencies', 'Rule of Law',
       'Elections and Political Processes', 'Local Government',
       'Legislature', 'Economic Governance', 'Disaster Recovery',
       'Economic Growth', 'Media', 'Civil Society',
       'Agriculture and Food Security', 'Governance', 'Healthcare',
       'Public Finance', 'Environment', 'Private Sector',
       'Democracy and Governance', 'Gender Equality', 'Natural Resource',
       'Education'], dtype=object)

In [88]:
Independent_Agencies_count=df[df['sector'] == 'Independent Agencies' ].groupby('country')['sector'].count()
Independent_Agencies_count

country
Afghanistan    1
Djibouti       1
El Salvador    1
Guatemala      1
Indonesia      1
Jamaica        1
Madagascar     1
Mongolia       1
Philippines    3
Name: sector, dtype: int64

In [89]:
Rule_of_Law_count=df[df['sector'] == 'Rule of Law' ].groupby('country')['sector'].count()
Rule_of_Law_count

country
Afghanistan                     2
Albania                         3
Azerbaijan                      1
Bangladesh                      1
Bosnia and Herzegovina          3
Cambodia                        5
Colombia                        2
Democratic Republic of Congo    1
Dominican Republic              5
East Timor                      4
Egypt                           2
El Salvador                     2
Georgia                         3
Guatemala                       2
Guyana                          1
Honduras                        1
Indonesia                       6
Jordan                          2
Kazakhstan                      4
Kosovo                          2
Kyrgyzstan                      5
Lebanon                         1
Libya                           1
Macedonia                       3
Mexico                          1
Moldova                         2
Mongolia                        1
Montenegro                      1
Multiple                        1
Nepal                           1
Nicaragua                       1
Panama                          1
Paraguay                        2
Peru                            1
Philippines                     2
Russia                          2
Serbia                          2
Ukraine                         3
West Bank and Gaza              3
Zambia                          1
Name: sector, dtype: int64

In [90]:
Elections_and_Political_Processes_count=df[df['sector'] == 'Elections and Political Processes' ].groupby('country')['sector'].count()
Elections_and_Political_Processes_count

country
Afghanistan    4
Iraq           1
Philippines    1
Name: sector, dtype: int64

In [91]:
Local_Government_count=df[df['sector'] == 'Local Government' ].groupby('country')['sector'].count()
Local_Government_count

country
Afghanistan                     11
Albania                          2
Angola                           1
Armenia                          1
Bangladesh                       1
Bolivia                          2
Bosnia and Herzegovina           1
Bulgaria                         1
Burundi                          2
Colombia                         2
Democratic Republic of Congo     1
East Timor                       1
Ecuador                          3
Ethiopia                         1
Ghana                            1
Guatemala                        2
Haiti                            1
Honduras                         1
Indonesia                        3
Iraq                             4
Jordan                           1
Kenya                            1
Kosovo                           3
Lebanon                          4
Liberia                          1
Macedonia                        3
Mali                             1
Mexico                           1
Moldova                          1
Mongolia                         1
Morocco                          2
Mozambique                       1
Nepal                            1
Nicaragua                        1
Pakistan                         1
Peru                             3
Philippines                      2
Russia                           1
Sri Lanka                        1
Ukraine                          1
West Bank and Gaza               2
Name: sector, dtype: int64

In [92]:
Legislature_count=df[df['sector'] == 'Legislature' ].groupby('country')['sector'].count()
Legislature_count

country
Afghanistan           1
Azerbaijan            1
Indonesia             1
Iraq                  1
Jordan                1
Kenya                 1
Morocco               1
Serbia                1
West Bank and Gaza    1
Name: sector, dtype: int64

In [93]:
Economic_Governance_count=df[df['sector'] == 'Economic Governance' ].groupby('country')['sector'].count()
Economic_Governance_count

country
Afghanistan           2
West Bank and Gaza    1
Name: sector, dtype: int64

In [94]:
Disaster_Recovery_count=df[df['sector'] == 'Disaster Recovery' ].groupby('country')['sector'].count()
Disaster_Recovery_count

country
Indonesia    1
Name: sector, dtype: int64

In [95]:
Economic_Growth_count=df[df['sector'] == 'Economic Growth' ].groupby('country')['sector'].count()
Economic_Growth_count

country
Afghanistan    3
Albania        1
Azerbaijan     1
Cambodia       1
Egypt          3
Guinea         1
Jordan         1
Kosovo         1
Kyrgyzstan     1
Laos           1
Liberia        2
Moldova        2
Mongolia       1
Morocco        2
Multiple       1
Pakistan       1
Philippines    2
Ukraine        1
Vietnam        2
Name: sector, dtype: int64

In [96]:
Media_count=df[df['sector'] == 'Media' ].groupby('country')['sector'].count()
Media_count

country
Afghanistan    1
Mongolia       1
Nicaragua      1
Sri Lanka      1
Name: sector, dtype: int64

In [97]:
Civil_Society_count=df[df['sector'] == 'Civil Society' ].groupby('country')['sector'].count()
Civil_Society_count

country
Afghanistan               1
Armenia                   3
Azerbaijan                1
Bosnia and Herzegovina    1
Dominican Republic        1
Egypt                     1
Indonesia                 2
Kyrgyzstan                1
Lebanon                   2
Macedonia                 1
Moldova                   1
Mongolia                  1
Multiple                  1
Nepal                     1
Nicaragua                 2
Pakistan                  3
Peru                      1
Philippines               2
Russia                    1
Serbia                    1
Thailand                  1
Ukraine                   1
West Bank and Gaza        1
Yemen                     1
Name: sector, dtype: int64

In [98]:
Agriculture_and_Food_Security_count=df[df['sector'] == 'Agriculture and Food Security' ].groupby('country')['sector'].count()
Agriculture_and_Food_Security_count

country
Afghanistan     1
Nigeria         1
Sierra Leone    1
Name: sector, dtype: int64

In [99]:
Governance_count=df[df['sector'] == 'Governance' ].groupby('country')['sector'].count()
Governance_count

country
Afghanistan               1
Bangladesh                1
Bosnia and Herzegovina    1
Dominican Republic        1
East Timor                1
Georgia                   1
Honduras                  1
Indonesia                 1
Iraq                      2
Malawi                    1
Moldova                   1
Mongolia                  1
Montenegro                2
Morocco                   1
Nigeria                   1
SENEGAL                   1
Sri Lanka                 1
Turkmenistan              1
West Bank and Gaza        1
Yemen                     1
Zambia                    1
Name: sector, dtype: int64

In [100]:
Healthcare_count=df[df['sector'] == 'Healthcare' ].groupby('country')['sector'].count()
Healthcare_count

country
Albania               1
Cambodia              1
Multiple              1
Paraguay              1
Rwanda                1
West Bank and Gaza    1
Yemen                 1
Name: sector, dtype: int64

In [101]:
Public_Finance_count=df[df['sector'] == 'Public Finance' ].groupby('country')['sector'].count()
Public_Finance_count

country
Albania        1
Azerbaijan     1
El Salvador    1
Guyana         1
Indonesia      1
Jordan         2
Kenya          2
Nigeria        1
Paraguay       1
Serbia         1
Uganda         2
Name: sector, dtype: int64

In [102]:
Environment_count=df[df['sector'] == 'Environment' ].groupby('country')['sector'].count()
Environment_count

country
Egypt    2
Name: sector, dtype: int64

In [103]:
Private_Sector_count=df[df['sector'] == 'Private Sector' ].groupby('country')['sector'].count()
Private_Sector_count

country
Egypt                                 1
Kyrgyzstan, Kazakhstan, Tajikistan    1
Mongolia                              1
Russia                                1
Name: sector, dtype: int64

In [104]:
Democracy_and_Governance_count=df[df['sector'] == 'Democracy and Governance' ].groupby('country')['sector'].count()
Democracy_and_Governance_count

country
Indonesia    1
Nigeria      1
Name: sector, dtype: int64

In [105]:
Gender_Equality_count=df[df['sector'] == 'Gender Equality' ].groupby('country')['sector'].count()
Gender_Equality_count

country
Kyrgyzstan, Kazakhstan, Tajikistan, Uzbekistan, Turkmenistan    1
Name: sector, dtype: int64

In [106]:
Natural_Resource_count=df[df['sector'] == 'Natural Resource' ].groupby('country')['sector'].count()
Natural_Resource_count

country
Sierra Leone    1
Name: sector, dtype: int64

In [107]:
Education_count=df[df['sector'] == 'Education' ].groupby('country')['sector'].count()
Education_count

country
Ukraine    2
Name: sector, dtype: int64

In [108]:
import functools

df1s = [df_dominant_topic, Independent_Agencies_count, Rule_of_Law_count,
       Elections_and_Political_Processes_count, Local_Government_count,
       Legislature_count, Economic_Governance_count, Disaster_Recovery_count,
        Economic_Growth_count, Media_count, Civil_Society_count,
        Agriculture_and_Food_Security_count, Governance_count, Healthcare_count,
        Public_Finance_count, Environment_count, Private_Sector_count,
        Democracy_and_Governance_count, Gender_Equality_count, Natural_Resource_count,
        Education_count]

df_sector= functools.reduce(lambda left,right: pd.merge(left,right,on=["country"], how="left"), df1s).fillna(0)
df_sector

,country,duration_mean,duration_min,duration_max,duration_median,topic0_mean,topic0_min,topic0_max,topic0_median,topic1_mean,...,sector_x,sector_y,sector_x,sector_y,sector_x,sector_y,sector_x,sector_y,sector_x,sector_y
0,Afghanistan,3.071429,0,7,3.0,0.036429,0.03,0.06,0.030,0.037857,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Albania,3.750000,2,5,3.5,0.037500,0.03,0.05,0.040,0.078750,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Angola,5.000000,5,5,5.0,0.030000,0.03,0.03,0.030,0.030000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Armenia,4.250000,4,5,4.0,0.035000,0.03,0.04,0.035,0.035000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Azerbaijan,2.800000,1,4,3.0,0.032000,0.03,0.04,0.030,0.032000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Ukraine,3.375000,2,5,3.0,0.035000,0.03,0.04,0.035,0.041250,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
70,Vietnam,3.500000,3,4,3.5,0.040000,0.04,0.04,0.040,0.040000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71,West Bank and Gaza,4.200000,2,6,4.5,0.034000,0.03,0.05,0.030,0.034000,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72,Yemen,4.000000,3,5,4.0,0.036667,0.03,0.04,0.040,0.036667,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73,Zambia,2.500000,2,3,2.5,0.035000,0.03,0.04,0.035,0.035000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [109]:
df_sector.columns.values[-1]
df_sector.columns.values[-1]='Education_count'

In [110]:
df_sector.columns.values[-2]
df_sector.columns.values[-2]='Natural_Resource_count'

In [111]:
df_sector.columns.values[-3]
df_sector.columns.values[-3]='Gender_Equality_count'

In [112]:
df_sector.columns.values[-4]
df_sector.columns.values[-4]='Democracy_and_Governance_count'

In [113]:
df_sector.columns.values[-5]
df_sector.columns.values[-5]='Private_Sector_count'

In [114]:
df_sector.columns.values[-6]
df_sector.columns.values[-6]='Environment_count'

In [115]:
df_sector.columns.values[-7]
df_sector.columns.values[-7]='Public_Finance_count'

In [116]:
df_sector.columns.values[-8]
df_sector.columns.values[-8]='Healthcare_count'

In [117]:
df_sector.columns.values[-9]
df_sector.columns.values[-9]='Governance_count'

In [118]:
df_sector.columns.values[-10]
df_sector.columns.values[-10]='Agriculture_and_Food_Security_count'

In [119]:
df_sector.columns.values[-11]
df_sector.columns.values[-11]='Civil_Society_count'

In [120]:
df_sector.columns.values[-12]
df_sector.columns.values[-12]='Media_count'

In [121]:
df_sector.columns.values[-13]
df_sector.columns.values[-13]='Economic_Growth_count'

In [122]:
df_sector.columns.values[-14]
df_sector.columns.values[-14]='Disaster_Recovery_count'

In [123]:
df_sector.columns.values[-15]
df_sector.columns.values[-15]='Economic_Governance_count'

In [124]:
df_sector.columns.values[-16]
df_sector.columns.values[-16]='Legislature_count'

In [125]:
df_sector.columns.values[-17]
df_sector.columns.values[-17]='Local_Government_count'

In [126]:
df_sector.columns.values[-18]
df_sector.columns.values[-18]='Elections_and_Political_Processes_count'

In [127]:
df_sector.columns.values[-19]
df_sector.columns.values[-19]='Rule_of_Law_count'

In [128]:
df_sector.columns.values[-20]
df_sector.columns.values[-20]='Independent_Agencies_count'

In [129]:
df_sector

,country,duration_mean,duration_min,duration_max,duration_median,topic0_mean,topic0_min,topic0_max,topic0_median,topic1_mean,...,Agriculture_and_Food_Security_count,Governance_count,Healthcare_count,Public_Finance_count,Environment_count,Private_Sector_count,Democracy_and_Governance_count,Gender_Equality_count,Natural_Resource_count,Education_count
0,Afghanistan,3.071429,0,7,3.0,0.036429,0.03,0.06,0.030,0.037857,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Albania,3.750000,2,5,3.5,0.037500,0.03,0.05,0.040,0.078750,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Angola,5.000000,5,5,5.0,0.030000,0.03,0.03,0.030,0.030000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Armenia,4.250000,4,5,4.0,0.035000,0.03,0.04,0.035,0.035000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Azerbaijan,2.800000,1,4,3.0,0.032000,0.03,0.04,0.030,0.032000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Ukraine,3.375000,2,5,3.0,0.035000,0.03,0.04,0.035,0.041250,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
70,Vietnam,3.500000,3,4,3.5,0.040000,0.04,0.04,0.040,0.040000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71,West Bank and Gaza,4.200000,2,6,4.5,0.034000,0.03,0.05,0.030,0.034000,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72,Yemen,4.000000,3,5,4.0,0.036667,0.03,0.04,0.040,0.036667,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73,Zambia,2.500000,2,3,2.5,0.035000,0.03,0.04,0.035,0.035000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [130]:
df2=df_sector[["Independent_Agencies_count","Rule_of_Law_count",
       "Elections_and_Political_Processes_count", "Local_Government_count",
       "Legislature_count", "Economic_Governance_count", "Disaster_Recovery_count",
        "Economic_Growth_count", "Media_count", "Civil_Society_count",
        "Agriculture_and_Food_Security_count", "Governance_count", "Healthcare_count",
        "Public_Finance_count", "Environment_count", "Private_Sector_count",
        "Democracy_and_Governance_count","Gender_Equality_count", "Natural_Resource_count",
        "Education_count"]]
df2

,Independent_Agencies_count,Rule_of_Law_count,Elections_and_Political_Processes_count,Local_Government_count,Legislature_count,Economic_Governance_count,Disaster_Recovery_count,Economic_Growth_count,Media_count,Civil_Society_count,Agriculture_and_Food_Security_count,Governance_count,Healthcare_count,Public_Finance_count,Environment_count,Private_Sector_count,Democracy_and_Governance_count,Gender_Equality_count,Natural_Resource_count,Education_count
0,1.0,2.0,4.0,11.0,1.0,2.0,0.0,3.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,3.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,0.0,3.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
70,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
71,0.0,3.0,0.0,2.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [131]:
df_sector["max_count_sector_categories"]=df2.eq(df2.max(1), axis=0).dot(df2.columns)
df_sector

,country,duration_mean,duration_min,duration_max,duration_median,topic0_mean,topic0_min,topic0_max,topic0_median,topic1_mean,...,Governance_count,Healthcare_count,Public_Finance_count,Environment_count,Private_Sector_count,Democracy_and_Governance_count,Gender_Equality_count,Natural_Resource_count,Education_count,max_count_sector_categories
0,Afghanistan,3.071429,0,7,3.0,0.036429,0.03,0.06,0.030,0.037857,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Local_Government_count
1,Albania,3.750000,2,5,3.5,0.037500,0.03,0.05,0.040,0.078750,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Rule_of_Law_count
2,Angola,5.000000,5,5,5.0,0.030000,0.03,0.03,0.030,0.030000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Local_Government_count
3,Armenia,4.250000,4,5,4.0,0.035000,0.03,0.04,0.035,0.035000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Civil_Society_count
4,Azerbaijan,2.800000,1,4,3.0,0.032000,0.03,0.04,0.030,0.032000,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,Rule_of_Law_countLegislature_countEconomic_Gro...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Ukraine,3.375000,2,5,3.0,0.035000,0.03,0.04,0.035,0.041250,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,Rule_of_Law_count
70,Vietnam,3.500000,3,4,3.5,0.040000,0.04,0.04,0.040,0.040000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Economic_Growth_count
71,West Bank and Gaza,4.200000,2,6,4.5,0.034000,0.03,0.05,0.030,0.034000,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rule_of_Law_count
72,Yemen,4.000000,3,5,4.0,0.036667,0.03,0.04,0.040,0.036667,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Civil_Society_countGovernance_countHealthcare_...
73,Zambia,2.500000,2,3,2.5,0.035000,0.03,0.04,0.035,0.035000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Rule_of_Law_countGovernance_count

In [132]:
df_sector.to_csv('df_sector_country.csv')