In [5]:
import pandas as pd
import numpy as np

In [8]:
df5 = pd.read_csv("WDIData.csv")
df5.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Arab World,ARB,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World,ARB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,Account ownership at a financial institution o...,FX.OWN.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,30.27713,NaN,NaN,37.165211,NaN,NaN,NaN,NaN

In [9]:
df5['Indicator Code'].unique()

array(['EG.CFT.ACCS.ZS', 'EG.ELC.ACCS.ZS', 'EG.ELC.ACCS.RU.ZS', ...,
       'SP.M15.2024.FE.ZS', 'SP.M18.2024.FE.ZS', 'SH.DYN.AIDS.FE.ZS'],
      dtype=object)

In [10]:
df5['Indicator Code'].nunique()

1437

In [11]:
df5.shape

(379368, 66)

In [12]:
yr_list = ['2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019',]
df6 = df5.melt(id_vars =['Indicator Code','Country Name'], value_vars = yr_list, var_name ='Year', value_name ='Value') 
df6.head(20)

              Indicator Code Country Name  Year     Value
0             EG.CFT.ACCS.ZS   Arab World  2007       NaN
1             EG.ELC.ACCS.ZS   Arab World  2007       NaN
2          EG.ELC.ACCS.RU.ZS   Arab World  2007       NaN
3          EG.ELC.ACCS.UR.ZS   Arab World  2007       NaN
4             FX.OWN.TOTL.ZS   Arab World  2007       NaN
5          FX.OWN.TOTL.FE.ZS   Arab World  2007       NaN
6          FX.OWN.TOTL.MA.ZS   Arab World  2007       NaN
7          FX.OWN.TOTL.OL.ZS   Arab World  2007       NaN
8          FX.OWN.TOTL.40.ZS   Arab World  2007       NaN
9          FX.OWN.TOTL.PL.ZS   Arab World  2007       NaN
10         FX.OWN.TOTL.60.ZS   Arab World  2007       NaN
11         FX.OWN.TOTL.SO.ZS   Arab World  2007       NaN
12         FX.OWN.TOTL.YG.ZS   Arab World  2007       NaN
13  per_si_allsi.adq_pop_tot   Arab World  2007       NaN
14     per_allsp.adq_pop_tot   Arab World  2007       NaN
15  per_sa_allsa.adq_pop_tot   Arab World  2007       NaN
16  per_lm_alllm.adq_pop_tot   Arab World  2007       NaN
17               SE.PRM.TENR   Arab World  2007  83.03500
18            SE.PRM.TENR.FE   Arab World  2007  80.44079
19            SE.PRM.TENR.MA   Arab World  2007  85.56248

In [13]:
df6.shape

(4931784, 4)

In [16]:
df3 = pd.read_csv("USAID_Anticorruption_Projects_Database.csv")
df3.head()

,uuid,region,country,proj_nm,st_date,end_date,awd_amount,awd_value,implementer,sector,...,rfp_rftop,final_res,mind_eval,final_eval,audit,interim_rep,addl_docs,addl_info,corruption,stability
0,1,South and Central Asia (SCA),Afghanistan,Assistance for Afghanistan's Anti-Corruption A...,2010,2013,e) $25 M-$50 M,26642989,Management Systems International (MSI),"Independent Agencies, Civil Society",...,NaN,http://pdf.usaid.gov/pdf_docs/PA00JP3T.pdf,NaN,NaN,NaN,NaN,http://www.msiworldwide.com/project/supporting...,NaN,High Corruption,Unstable
1,2,South and Central Asia (SCA),Afghanistan,Rule of Law Stabilization Program - Formal Com...,2010,2012,e) $25 M-$50 M,33700000,TetraTech ARD,Rule of Law,...,NaN,NaN,NaN,http://pdf.usaid.gov/pdf_docs/PDACU496.pdf,NaN,NaN,NaN,NaN,Very High Corruption,Very Unstable
2,3,South and Central Asia (SCA),Afghanistan,Afghanistan Rule of Law Stabilization Project ...,2011,2012,c) $5 M-$10 M,10000000,"Checchi and Company Consulting, Inc.",Rule of Law,...,NaN,http://pdf.usaid.gov/pdf_docs/PDACY340.pdf,NaN,http://pdf.usaid.gov/pdf_docs/PDACW029.pdf,NaN,NaN,http://www.checchiconsulting.com/index.php?opt...,NaN,Very High Corruption,Very Unstable
3,4,South and Central Asia (SCA),Afghanistan,Political Party Assessment,2012,2012,a) <$1 M,NaN,"Checchi and Company Consulting, Inc.",Elections and Political Processes,...,NaN,http://pdf.usaid.gov/pdf_docs/PNADZ833.pdf,NaN,NaN,NaN,NaN,NaN,NaN,Very High Corruption,Very Unstable
4,30,Europe and Eurasia (E&E),Albania,Justice Sector Strengthening Project (JuST),2010,2015,c) $5 M-$10 M,9012613,Chemonics,"Rule of Law, Civil Society",...,https://www.fbo.gov/index?s=opportunity&mode=f...,NaN,NaN,NaN,NaN,http://pdf.usaid.gov/pdf_docs/PA00HWM1.pdf,NaN,NaN,High Corruption,Unstable

In [17]:
df3.shape

(315, 24)

In [14]:
df4 = df3.merge(df6, how='left',left_on=['end_date','country'], right_on=['Year','Country Name'])
df4.head()

,uuid,region,country,proj_nm,st_date,end_date,awd_amount,awd_value,implementer,sector,...,audit,interim_rep,addl_docs,addl_info,corruption,stability,Indicator Code,Country Name,Year,Value
0,1,South and Central Asia (SCA),Afghanistan,Assistance for Afghanistan's Anti-Corruption A...,2010,2013,e) $25 M-$50 M,26642989,Management Systems International (MSI),"Independent Agencies, Civil Society",...,NaN,NaN,http://www.msiworldwide.com/project/supporting...,NaN,High Corruption,Unstable,EG.CFT.ACCS.ZS,Afghanistan,2013,26.170000
1,1,South and Central Asia (SCA),Afghanistan,Assistance for Afghanistan's Anti-Corruption A...,2010,2013,e) $25 M-$50 M,26642989,Management Systems International (MSI),"Independent Agencies, Civil Society",...,NaN,NaN,http://www.msiworldwide.com/project/supporting...,NaN,High Corruption,Unstable,EG.ELC.ACCS.ZS,Afghanistan,2013,68.933266
2,1,South and Central Asia (SCA),Afghanistan,Assistance for Afghanistan's Anti-Corruption A...,2010,2013,e) $25 M-$50 M,26642989,Management Systems International (MSI),"Independent Agencies, Civil Society",...,NaN,NaN,http://www.msiworldwide.com/project/supporting...,NaN,High Corruption,Unstable,EG.ELC.ACCS.RU.ZS,Afghanistan,2013,61.282199
3,1,South and Central Asia (SCA),Afghanistan,Assistance for Afghanistan's Anti-Corruption A...,2010,2013,e) $25 M-$50 M,26642989,Management Systems International (MSI),"Independent Agencies, Civil Society",...,NaN,NaN,http://www.msiworldwide.com/project/supporting...,NaN,High Corruption,Unstable,EG.ELC.ACCS.UR.ZS,Afghanistan,2013,92.673767
4,1,South and Central Asia (SCA),Afghanistan,Assistance for Afghanistan's Anti-Corruption A...,2010,2013,e) $25 M-$50 M,26642989,Management Systems International (MSI),"Independent Agencies, Civil Society",...,NaN,NaN,http://www.msiworldwide.com/project/supporting...,NaN,High Corruption,Unstable,FX.OWN.TOTL.ZS,Afghanistan,2013,NaN

In [15]:
df4.shape

(379419, 28)